# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-23 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('private', '培训机构'), ('university', '高等院校')], default='university', max_length=20, verbose_name='机构类别'),
        ),
    ]
