# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
