# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='课程类别'),
        ),
    ]
