# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='课程标签'),
        ),
    ]
