# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180725_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
