# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
        ('course', '0008_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banner', models.BooleanField(default=False)),
                ('course_know', models.CharField(blank=True, max_length=100, null=True, verbose_name='课程须知')),
                ('teacher_enlighten', models.CharField(blank=True, max_length=100, null=True, verbose_name='老师指点')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('abstract', models.CharField(max_length=500, verbose_name='课程简介')),
                ('detail', models.TextField(verbose_name='课程详情')),
                ('degree', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('difficulty', '困难')], default='easy', max_length=30, verbose_name='课程难度')),
                ('period', models.IntegerField(default=0, verbose_name='课时(按分钟计)')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('tag', models.CharField(blank=True, max_length=10, null=True, verbose_name='课程标签')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='课程点击数')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='课程类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='授课老师')),
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
            },
        ),
    ]
