# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_bannercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercourse',
            name='org',
        ),
        migrations.RemoveField(
            model_name='bannercourse',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='BannerCourse',
        ),
    ]
