# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-26 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180723_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
