# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('forget', '忘记密码'), ('register', '注册'), ('modify', '更换邮箱')], max_length=20, verbose_name='发送类型'),
        ),
    ]
